server:
  port: 8084
  servlet:
    context-path: /payment-service


#  8084/payment-service/api/v1


spring:
  application:
    name: payment-service



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/